//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SphereProcurement
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public string itemId { get; set; }
        public string name { get; set; }
        public string category { get; set; }
        public string brand { get; set; }
        public string description { get; set; }
        public string source { get; set; }
        public Nullable<double> maxStock { get; set; }
        public Nullable<double> currentStock { get; set; }
        public string unit { get; set; }
        public string status { get; set; }
    }
}
