//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SphereProcurement
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public string paymentId { get; set; }
        public string purchaseOrderId { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<System.DateTime> paidOn { get; set; }
        public string paidBy { get; set; }
    }
}
