//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SphereProcurement
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchaseRequestItem
    {
        public string requestItemId { get; set; }
        public string requestId { get; set; }
        public string supplierId { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<double> subTotal { get; set; }
        public string deliveryStatus { get; set; }
    }
}
