//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SphereProcurement
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchaseRequest
    {
        public string requestId { get; set; }
        public Nullable<double> totalAmount { get; set; }
        public string createdBy { get; set; }
        public string requestStatus { get; set; }
    }
}
