//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SphereProcurement
{
    using System;
    using System.Collections.Generic;
    
    public partial class siteManager
    {
        public string smanagerNo { get; set; }
        public string sname { get; set; }
        public string snic { get; set; }
        public string scontactNo { get; set; }
        public string site { get; set; }
        public Nullable<double> approvedValue { get; set; }
    }
}
