//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SphereProcurement
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_items
    {
        public string supItemId { get; set; }
        public string supplierId { get; set; }
        public string itemName { get; set; }
    
        public virtual supplier supplier { get; set; }
    }
}
